language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-19mode # JRuby (1.9)
  # Don't run on rubinius
  # - rbx
matrix:
fast_finish: true
allow_failures:
  - rvm: 1.9.3
  - rvm: 2.0.0
sudo: false
