# External config to match actions to sprite image names
sort_desc: "icons-famfamfam-arrow_down"
sort_asc: "icons-famfamfam-arrow_up"
info: "icons-famfamfam-information"
help: "icons-famfamfam-help"
show: "icons-famfamfam-magnifier"
back: "icons-famfamfam-arrow_undo"
add: "icons-famfamfam-add"
edit: "icons-famfamfam-wrench"
login: "icons-famfamfam-lock_open"
logout: "icons-famfamfam-lock"