# Configuration file for BobCat institutions.
NYU:
  default: true
  name: NYU Libraries
  auth:
    code: NYU
  views:
    css: bobcat
    dir: nyu
    breadcrumbs:
      title: NYU Libraries
      url: http://library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: http://bobcatdev.library.nyu.edu
        tip: 'Books & e-books, journals & e-journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings'
      remote:
        display: 'Articles & Databases'
        url: https://webdev1.library.nyu.edu/arch
        tip: by Subject and Content Type
      databases:
        display: Databases A-Z
        url: https://webdev1.library.nyu.edu/arch/databases/alphabetical/
        tip: All databases by title
      journals:
        display: Journals
        tip: Find e-journals by title or locate a known article
      reserves:
        display: Course Reserves
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&amp;vid=NYU&amp;tab=reserves'
        tip: 'Search by instructor, course name, course title, etc.'

NYUAD:
  name: NYU Abu Dhabi Library
  views:
    css: bobcat_nyuad
    dir: nyuad
    breadcrumbs:
      title: NYUAD Library
      url: http://nyuad.nyu.edu/academics/library/index.html
    tabs:
      all:
        display: 'Books & More'
        url: http://bobcatdev.library.nyu.edu/nyuad
        tip: 'Books, E-Books, Journal Titles, Audio, Video & More'
      remote:
        display: 'Articles & Databases'
        url: https://webdev1.library.nyu.edu/arch/nyuad
        tip: Sorted by Subject and Content Type
      databases:
        display: Databases A-Z
        url: https://webdev1.library.nyu.edu/arch/nyuad/databases/alphabetical/
        tip: All Databases by Title
      journals:
        display: Journals
        tip: Find E-journals by Title or Locate a Known Article
      reserves:
        display: Course Reserves
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYUAD&tab=nyuadcr'
        tip: 'Search by Course or Professor'

CU:
  name: The Cooper Union Library
  auth:
    code: CU
  views:
    css: bobcat_cu
    dir: cu
    breadcrumbs:
      title: Cooper Union Library
      url: http://library.cooper.edu
    tabs:
      all:
        display: Consortium Catalog
        url: http://bobcatdev.library.nyu.edu/cooper
        tip: 'Books & e-books, journals & e-journals, scripts, scores, archival materials, videos, sound recordings, and other materials in the Consortium libraries'
      cu:
        display: Cooper Library Catalog
        url: "http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=CU&tab=cu"
        tip: 'Books & e-books, journals & e-journals, videos, and other materials in the Cooper Union Library'
      journals:
        display: E-Journals
        tip: Browse e-journals by title or search for a specific article
      reserves:
        display: Course Reserves
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&amp;vid=CU&amp;tab=cucr'
        tip: 'Search course reserves by instructor, course name or number, author, title, and other terms'

NS:
  name: New School Libraries
  auth:
    code: NS
  views:
    css: bobcat_ns
    dir: ns
    breadcrumbs:
      title: New School Libraries
      url: http://library.newschool.edu
    tabs:
      all:
        display: Find resources in All Consortium Libraries
        url: http://bobcatdev.library.nyu.edu/newschool
        tip: Find resources in All Consortium Libraries
      ns:
        display: New School Resources
        url: "http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NS&tab=ns"
        tip: Find New School Resources
      remote:
        display: Articles and Databases
        url: https://webdev1.library.nyu.edu/arch/ns
        tip: 'Search for articles, images and media by subject'
      databases:
        display: Databases A-Z
        url: https://webdev1.library.nyu.edu/arch/ns/databases/alphabetical/
        tip: All databases by title
      journals:
        display: Journals A-Z
        tip: Locate journals by title or citation
      reserves:
        display: Course Reserves
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&amp;vid=NS&amp;tab=nscr'
        tip: 'Search for Reserves by title or instructor name'
