# Configuration file for BobCat institutions.
NYU:
  default: true
  name: NYU Libraries
  auth:
    code: NYU
  getit_url: https://getit.library.nyu.edu/nyu/resolve?
  views:
    css: application
    dir: nyu
    breadcrumbs:
      title: NYU Libraries
      url: http://library.nyu.edu
    ill:
      link_html: My interlibrary loan (ILL)
      url: http://ill.library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: http://bobcat.library.nyu.edu
        tip: 'Books & e-books, journals & e-journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings'
      remote:
        display: 'Articles & Databases'
        url: https://arch.library.nyu.edu
        tip: by Subject and Content Type
      databases:
        display: Databases A-Z
        url: https://arch.library.nyu.edu/databases/alphabetical/
        tip: All databases by title
      journals:
        display: Journals
        tip: Find e-journals by title or locate a known article
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYU&tab=reserves'
        tip: 'Search by instructor, course name, course title, etc.'

NYUSH:
  name: NYU Shanghai Library
  getit_url: https://getit.library.nyu.edu/nyush/resolve?
  views:
    css: application_nyush
    dir: nyush
    breadcrumbs:
      title: NYU Shanghai Library
      url: http://library.nyu.edu/shanghai
    ill:
      link_html: My interlibrary loan (ILL)
      url: http://ill.library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: http://bobcat.library.nyu.edu/nyush
        tip: 'Books & e-books, journals & e-journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings'
      remote:
        display: 'Articles & Databases'
        url: https://arch.library.nyu.edu/nyush
        tip: by Subject and Content Type
      databases:
        display: Databases A-Z
        url: https://arch.library.nyu.edu/nyush/databases/alphabetical/
        tip: All databases by title
      journals:
        display: Journals
        tip: Find e-journals by title or locate a known article
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYUSH&tab=nyushcr'
        tip: 'Search by instructor, course name, course title, etc.'

NYUAD:
  name: NYU Abu Dhabi Library
  getit_url: https://getit.library.nyu.edu/nyuad/resolve?
  views:
    css: application_nyuad
    dir: nyuad
    breadcrumbs:
      title: NYUAD Library
      url: http://nyuad.nyu.edu/academics/library/index.html
    ill:
      link_html: My interlibrary loan (ILL)
      url: http://ill.library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: http://bobcat.library.nyu.edu/nyuad
        tip: 'Books, E-Books, Journal Titles, Audio, Video & More'
      remote:
        display: 'Articles & Databases'
        url: https://arch.library.nyu.edu/nyuad
        tip: Sorted by Subject and Content Type
      databases:
        display: Databases A-Z
        url: https://arch.library.nyu.edu/nyuad/databases/alphabetical/
        tip: All Databases by Title
      journals:
        display: Journals
        tip: Find E-journals by Title or Locate a Known Article
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYUAD&tab=nyuadcr'
        tip: 'Search by Course or Professor'

CU:
  name: The Cooper Union Library
  getit_url: https://getit.library.nyu.edu/cu/resolve?
  auth:
    code: CU
  views:
    css: application_cu
    dir: cu
    breadcrumbs:
      title: Cooper Union Library
      url: http://library.cooper.edu
    tabs:
      all:
        display: Consortium Catalog
        url: http://bobcat.library.nyu.edu/cooper
        tip: 'Books & e-books, journals & e-journals, scripts, scores, archival materials, videos, sound recordings, and other materials in the Consortium libraries'
      cu:
        display: Cooper Library Catalog
        url: "http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=CU&tab=cu"
        tip: 'Books & e-books, journals & e-journals, videos, and other materials in the Cooper Union Library'
      journals:
        display: E-Journals
        tip: Browse e-journals by title or search for a specific article
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=CU&tab=cucr'
        tip: 'Search course reserves by instructor, course name or number, author, title, and other terms'

NS:
  name: New School Libraries
  getit_url: https://getit.library.nyu.edu/ns/resolve?
  auth:
    code: NS
  views:
    css: application_ns
    dir: ns
    breadcrumbs:
      title: New School Libraries
      url: http://library.newschool.edu
    ill:
      link_html: My interlibrary loan (ILL)
      url: http://ill.library.nyu.edu
    tabs:
      all:
        display: Consortium Libraries
        url: http://bobcat.library.nyu.edu/newschool
        tip: Find resources in All Consortium Libraries
      ns:
        display: New School Resources
        url: "http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NS&tab=ns"
        tip: Find New School Resources
      remote:
        display: Articles and Databases
        url: https://arch.library.nyu.edu/ns
        tip: 'Search for articles, images and media by subject'
      databases:
        display: Databases A-Z
        url: https://arch.library.nyu.edu/ns/databases/alphabetical/
        tip: All databases by title
      journals:
        display: Journals A-Z
        tip: Locate journals by title or citation
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NS&tab=nscr'
        tip: 'Search for Reserves by title or instructor name'

HSL:
  name: NYU Health Sciences Libraries
  getit_url: https://getit.library.nyu.edu/hsl/resolve?
  auth:
    code: HSL
  views:
    css: application_hsl
    dir: hsl
    breadcrumbs:
      title: NYU Health Sciences Libraries
      url: http://hsl.med.nyu.edu/
    tabs:
      all:
        display: HSLCat
        url: "http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=HSL&tab=all"
        tip: "Keyword search: library catalog"
      eresources:
        display: Search e-Resources
        tip: "Title search: databases, ejournals, websites, etc."
      journals:
        display: Journals A-Z
        tip: Locate journals by title or citation

NYSID:
  name: New York School of Interior Design
  views:
    css: application_nysid
    dir: nysid
    breadcrumbs:
      title: New York School of Interior Design Library
      url: http://nysidlibrary.org/
    ill:
      link_html: My interlibrary loan (ILL)
      url: http://ill.library.nyu.edu
    tabs:
      nysid:
        display: NYSID Resources
        url: http://bobcat.library.nyu.edu/nysid
        tip: Find New York School of Interior Design Resources
      all:
        display: 'Books & More'
        url: http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYSID&tab=all
        tip: 'Find Resources in All BobCat Libraries'
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYSID&tab=reserves'
        tip: 'Search for books on reserve by instructor, course name or number, author, title, and other terms."'